# Generated by Django 4.2 on 2024-03-15 05:47

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email confirmation code'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date email was confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Пользователь заблокирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Запись удалена'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=True, verbose_name='Email подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_confirmed',
            field=models.BooleanField(default=True, verbose_name='Номер телефона подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_auth_only',
            field=models.BooleanField(default=False, verbose_name='Авторизация только через keycloak'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts_count',
            field=models.IntegerField(default=0, verbose_name='Invalid log in attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_password_update',
            field=models.BooleanField(default=False, verbose_name='Необходима смена пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='New email'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='New phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последней смены пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_code_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code sent date'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmation_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone confirmation code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date phone was confirmed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
