# Generated by Django 3.2.16 on 2022-10-20 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail инвайта')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор компании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('token', models.CharField(max_length=16, verbose_name='Код подтверждения добавления')),
                ('status', django_fsm.FSMField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('declined', 'Отвергнут')], default='created', max_length=50, verbose_name='Статус инвайта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Инвайт в компанию',
                'verbose_name_plural': 'Инвайты в компании',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор компании')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован администратором компании')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercompany', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь компании',
                'verbose_name_plural': 'Пользователи компании',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
