# Generated by Django 3.2.16 on 2022-12-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usercompanyrole'),
        ('garpix_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usercompanyrole', verbose_name='Роль в компании'),
        ),
    ]
