# Generated by Django 3.2.16 on 2022-12-26 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_company', '0002_usercompany_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercompany', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
