# Generated by Django 3.2.16 on 2023-01-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usercompanyrole'),
        ('garpix_company', '0004_alter_usercompany_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetocompany',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usercompanyrole', verbose_name='Роль в компании'),
        ),
    ]
