# Generated by Django 3.2.16 on 2023-01-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_company', '0005_invitetocompany_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetocompany',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='is_admin',
        ),
    ]
