# Generated by Django 3.2.16 on 2023-01-26 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usercompanyrole_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_company', '0006_auto_20230126_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to='app.company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
