# Generated by Django 3.2.16 on 2023-01-30 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_usercompanyrole_role_type'),
        ('garpix_company', '0007_auto_20230126_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetocompany',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='invitetocompany',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail инвайта'),
        ),
        migrations.AlterField(
            model_name='invitetocompany',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercompanyrole', verbose_name='Роль в компании'),
        ),
    ]
