# Generated by Django 3.2.17 on 2023-02-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_company', '0008_auto_20230130_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetocompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail инвайта'),
        ),
        migrations.AlterField(
            model_name='invitetocompany',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
