# Generated by Django 3.2.17 on 2023-05-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230511_1245'),
        ('garpix_company', '0009_auto_20230206_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
