# Generated by Django 4.2 on 2024-03-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_company', '0011_usercompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitetocompany',
            options={'ordering': ['-id'], 'verbose_name': 'Инвайт в компанию | Invite to company', 'verbose_name_plural': 'Инвайты в компании | Invites to companies'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Пользователь компании | Company user', 'verbose_name_plural': 'Пользователи компании | Company users'},
        ),
    ]
