# Generated by Django 3.2.16 on 2022-10-20 10:21

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('full_title', models.CharField(max_length=255, verbose_name='Полное название')),
                ('inn', models.CharField(max_length=15, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('kpp', models.CharField(max_length=50, verbose_name='КПП')),
                ('bank_title', models.CharField(max_length=100, verbose_name='Наименование банка')),
                ('bic', models.CharField(max_length=100, verbose_name='БИК банка')),
                ('schet', models.CharField(max_length=50, verbose_name='Номер счета')),
                ('korschet', models.CharField(max_length=50, verbose_name='Кор. счет')),
                ('ur_address', models.CharField(max_length=300, verbose_name='Юридический адрес')),
                ('fact_address', models.CharField(max_length=300, verbose_name='Фактический адрес')),
                ('status', django_fsm.FSMField(choices=[('active', 'Активна'), ('banned', 'Забанена'), ('deleted', 'Удалена')], default='active', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
