# Generated by Django 3.2.16 on 2022-10-20 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_company', '0001_initial'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='participants',
            field=models.ManyToManyField(through='garpix_company.UserCompany', to=settings.AUTH_USER_MODEL, verbose_name='Участники компании'),
        ),
    ]
