# Generated by Django 3.2.16 on 2022-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221202_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль в компании',
                'verbose_name_plural': 'Роли в компаниях',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
