# Generated by Django 3.2.16 on 2023-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230126_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanyrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Админ'), ('owner', 'Владелец'), ('employee', 'Сотрудник')], default='employee', max_length=128, verbose_name='Тип'),
        ),
    ]
