# Generated by Django 3.2.17 on 2023-05-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_usercompanyrole_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован администратором компании')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to='app.company')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usercompanyrole', verbose_name='Роль в компании')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь компании',
                'verbose_name_plural': 'Пользователи компании',
                'abstract': False,
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='participants',
            field=models.ManyToManyField(through='app.UserCompany', to=settings.AUTH_USER_MODEL, verbose_name='Участники компании'),
        ),
    ]
