# Generated by Django 3.2.17 on 2023-06-21 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20230511_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fact_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ur_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
