# Generated by Django 3.2.17 on 2023-06-21 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_company', '0011_usercompany'),
        ('app', '0009_auto_20230621_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='participants',
            field=models.ManyToManyField(through='garpix_company.UserCompany', to=settings.AUTH_USER_MODEL, verbose_name='Участники компании'),
        ),
    ]
