# Generated by Django 4.2 on 2024-03-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_company_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': 'Компания | Company', 'verbose_name_plural': 'Компании | Companies'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Пользователь компании | Company user', 'verbose_name_plural': 'Пользователи компании | Company users'},
        ),
        migrations.AlterModelOptions(
            name='usercompanyrole',
            options={'ordering': ['-id'], 'verbose_name': 'Роль в компании | User company role', 'verbose_name_plural': 'Роли в компаниях | User companies roles'},
        ),
    ]
